"""add_order_payments_table

Revision ID: 591199a388cb
Revises: d1d2dcdf418e
Create Date: 2026-03-26 01:08:53.864225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591199a388cb'
down_revision: Union[str, None] = 'd1d2dcdf418e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_ref', sa.String(length=64), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_payments_order_id'), 'order_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_payments_payment_ref'), 'order_payments', ['payment_ref'], unique=True)
    op.drop_constraint(op.f('loading_docks_assigned_vehicle_id_fkey'), 'loading_docks', type_='foreignkey')
    op.create_foreign_key(None, 'loading_docks', 'logistics_vehicles', ['assigned_vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loading_docks', type_='foreignkey')
    op.create_foreign_key(op.f('loading_docks_assigned_vehicle_id_fkey'), 'loading_docks', 'logistics_vehicles', ['assigned_vehicle_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_order_payments_payment_ref'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_order_id'), table_name='order_payments')
    op.drop_table('order_payments')
    # ### end Alembic commands ###
