"""add priority to orders

Revision ID: c7a9c989abe7
Revises: 022_notification_audience
Create Date: 2026-03-31 01:59:59.185266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a9c989abe7'
down_revision: Union[str, None] = '022_notification_audience'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('priority', sa.String(length=10), nullable=False, server_default='NORMAL'))
    op.execute("UPDATE orders SET priority = 'NORMAL' WHERE priority IS NULL")
    op.create_index(op.f('ix_orders_priority'), 'orders', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_priority'), table_name='orders')
    op.drop_column('orders', 'priority')
    # ### end Alembic commands ###
