"""Add restock requests

Revision ID: d716df40f352
Revises: 012
Create Date: 2026-03-20 17:20:20.413141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd716df40f352'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restock_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_requests_item_id'), 'restock_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_restock_requests_warehouse_id'), 'restock_requests', ['warehouse_id'], unique=False)
    op.drop_constraint(op.f('customer_quotes_reference_code_key'), 'customer_quotes', type_='unique')
    op.drop_index(op.f('ix_customer_quotes_reference_code'), table_name='customer_quotes')
    op.create_index(op.f('ix_customer_quotes_reference_code'), 'customer_quotes', ['reference_code'], unique=True)
    op.drop_constraint(op.f('damage_reports_reference_code_key'), 'damage_reports', type_='unique')
    op.drop_index(op.f('ix_damage_reports_reference_code'), table_name='damage_reports')
    op.create_index(op.f('ix_damage_reports_reference_code'), 'damage_reports', ['reference_code'], unique=True)
    op.drop_index(op.f('ix_loading_docks_status'), table_name='loading_docks')
    op.drop_index(op.f('ix_loading_docks_warehouse_id'), table_name='loading_docks')
    op.drop_constraint(op.f('uq_loading_docks_warehouse_dock_number'), 'loading_docks', type_='unique')
    op.drop_constraint(op.f('logistics_return_cases_reference_code_key'), 'logistics_return_cases', type_='unique')
    op.drop_constraint(op.f('logistics_transactions_transaction_code_key'), 'logistics_transactions', type_='unique')
    op.drop_constraint(op.f('logistics_vehicles_code_key'), 'logistics_vehicles', type_='unique')
    op.drop_index(op.f('ix_packing_stations_warehouse_id'), table_name='packing_stations')
    op.drop_constraint(op.f('uq_packing_stations_warehouse_station'), 'packing_stations', type_='unique')
    op.drop_constraint(op.f('picked_items_order_id_fkey'), 'picked_items', type_='foreignkey')
    op.drop_constraint(op.f('picked_items_picked_by_fkey'), 'picked_items', type_='foreignkey')
    op.create_foreign_key(None, 'picked_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'picked_items', 'users', ['picked_by'], ['id'])
    op.drop_index(op.f('ix_quality_checks_order_id'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_warehouse_id'), table_name='quality_checks')
    op.create_unique_constraint(None, 'quality_checks', ['order_id'])
    op.drop_index(op.f('ix_return_gradings_rma_code'), table_name='return_gradings')
    op.drop_index(op.f('ix_return_gradings_status'), table_name='return_gradings')
    op.drop_index(op.f('ix_return_gradings_warehouse_id'), table_name='return_gradings')
    op.create_unique_constraint(None, 'return_gradings', ['rma_code'])
    op.drop_index(op.f('ix_warehouse_zone_metrics_metric_date'), table_name='warehouse_zone_metrics')
    op.drop_index(op.f('ix_warehouse_zone_metrics_warehouse_id'), table_name='warehouse_zone_metrics')
    op.drop_constraint(op.f('uq_zone_metrics_warehouse_zone_date'), 'warehouse_zone_metrics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_zone_metrics_warehouse_zone_date'), 'warehouse_zone_metrics', ['warehouse_id', 'zone_id', 'metric_date'])
    op.create_index(op.f('ix_warehouse_zone_metrics_warehouse_id'), 'warehouse_zone_metrics', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_zone_metrics_metric_date'), 'warehouse_zone_metrics', ['metric_date'], unique=False)
    op.drop_constraint(None, 'return_gradings', type_='unique')
    op.create_index(op.f('ix_return_gradings_warehouse_id'), 'return_gradings', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_return_gradings_status'), 'return_gradings', ['status'], unique=False)
    op.create_index(op.f('ix_return_gradings_rma_code'), 'return_gradings', ['rma_code'], unique=True)
    op.drop_constraint(None, 'quality_checks', type_='unique')
    op.create_index(op.f('ix_quality_checks_warehouse_id'), 'quality_checks', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_order_id'), 'quality_checks', ['order_id'], unique=True)
    op.drop_constraint(None, 'picked_items', type_='foreignkey')
    op.drop_constraint(None, 'picked_items', type_='foreignkey')
    op.create_foreign_key(op.f('picked_items_picked_by_fkey'), 'picked_items', 'users', ['picked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('picked_items_order_id_fkey'), 'picked_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_packing_stations_warehouse_station'), 'packing_stations', ['warehouse_id', 'station_number'])
    op.create_index(op.f('ix_packing_stations_warehouse_id'), 'packing_stations', ['warehouse_id'], unique=False)
    op.create_unique_constraint(op.f('logistics_vehicles_code_key'), 'logistics_vehicles', ['code'])
    op.create_unique_constraint(op.f('logistics_transactions_transaction_code_key'), 'logistics_transactions', ['transaction_code'])
    op.create_unique_constraint(op.f('logistics_return_cases_reference_code_key'), 'logistics_return_cases', ['reference_code'])
    op.create_unique_constraint(op.f('uq_loading_docks_warehouse_dock_number'), 'loading_docks', ['warehouse_id', 'dock_number'])
    op.create_index(op.f('ix_loading_docks_warehouse_id'), 'loading_docks', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_loading_docks_status'), 'loading_docks', ['status'], unique=False)
    op.drop_index(op.f('ix_damage_reports_reference_code'), table_name='damage_reports')
    op.create_index(op.f('ix_damage_reports_reference_code'), 'damage_reports', ['reference_code'], unique=False)
    op.create_unique_constraint(op.f('damage_reports_reference_code_key'), 'damage_reports', ['reference_code'])
    op.drop_index(op.f('ix_customer_quotes_reference_code'), table_name='customer_quotes')
    op.create_index(op.f('ix_customer_quotes_reference_code'), 'customer_quotes', ['reference_code'], unique=False)
    op.create_unique_constraint(op.f('customer_quotes_reference_code_key'), 'customer_quotes', ['reference_code'])
    op.drop_index(op.f('ix_restock_requests_warehouse_id'), table_name='restock_requests')
    op.drop_index(op.f('ix_restock_requests_item_id'), table_name='restock_requests')
    op.drop_table('restock_requests')
    # ### end Alembic commands ###
