"""
ai.py
Pydantic v2 request/response schemas for the AI chatbot endpoints.
"""
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


# ── Request Schemas ───────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's message to the AI chatbot.",
    )
    session_id: UUID | None = Field(
        default=None,
        description="Existing conversation session ID. Omit to start a new conversation.",
    )


# ── Response Schemas ──────────────────────────────────────────────────────────

class ChatResponse(BaseModel):
    session_id: UUID
    message: str
    intent: str | None = Field(
        default=None,
        description="Classified intent: db_query, general, greeting, error",
    )
    sql_generated: str | None = Field(
        default=None,
        description="The SQL query generated by the AI (if any). Useful for transparency.",
    )


class ConversationMessage(BaseModel):
    role: str = Field(description="'user' or 'assistant'")
    message: str
    intent: str | None = None
    sql_generated: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


class ConversationHistory(BaseModel):
    session_id: UUID
    messages: list[ConversationMessage]


class SessionListItem(BaseModel):
    session_id: UUID
    last_message: str
    message_count: int
    created_at: datetime


class SessionListResponse(BaseModel):
    sessions: list[SessionListItem]


# ── Escalation Schemas ────────────────────────────────────────────────────────

class EscalateRequest(BaseModel):
    reason: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Why this conversation needs human attention.",
    )


class EscalationResponse(BaseModel):
    id: UUID
    conversation_id: UUID
    reason: str
    escalated_to_user_id: UUID | None = None
    escalated_at: datetime
    resolved_at: datetime | None = None
    status: str

    model_config = {"from_attributes": True}


class EscalationListResponse(BaseModel):
    escalations: list[EscalationResponse]
