"""
ai.py
Pydantic v2 request/response schemas for the AI chatbot endpoints.
"""
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


# ── Request Schemas ───────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's message to the AI chatbot.",
    )
    context: str | None = Field(
        default=None,
        description="Optional module context such as warehouse_management or vendor_dashboard.",
    )
    session_id: UUID | None = Field(
        default=None,
        description="Existing conversation session ID. Omit to start a new conversation.",
    )
    order_id: UUID | None = Field(
        default=None,
        description="Linked order/shipment for support-chat flows.",
    )


class AgentReplyRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Human agent reply to append to an AI conversation session.",
    )


class ContactSubmissionCreatePublic(BaseModel):
    name: str = Field(..., min_length=2, max_length=255)
    email: str = Field(..., min_length=3, max_length=255)
    phone: str | None = Field(default=None, max_length=40)
    subject: str = Field(..., min_length=2, max_length=255)
    category: str = Field(default="general", min_length=2, max_length=50)
    priority: str = Field(default="medium", min_length=2, max_length=20)
    message: str = Field(..., min_length=5, max_length=5000)


class ContactSubmissionUpdate(BaseModel):
    status: str | None = Field(default=None, max_length=20)
    priority: str | None = Field(default=None, max_length=20)
    assigned_to_user_id: UUID | None = None
    notes: str | None = Field(default=None, max_length=5000)


class ContactSubmissionReplyRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=5000)


class SupportSessionEscalateRequest(BaseModel):
    reason: str = Field(..., min_length=1, max_length=1000)


# ── Response Schemas ──────────────────────────────────────────────────────────

class ChatResponse(BaseModel):
    session_id: UUID
    message: str
    intent: str | None = Field(
        default=None,
        description="Classified intent: db_query, general, greeting, error",
    )
    sql_generated: str | None = Field(
        default=None,
        description="The SQL query generated by the AI (if any). Useful for transparency.",
    )
    requires_human: bool = Field(
        default=False,
        description="Whether this response triggered or requires human support follow-up.",
    )
    human_handoff_reason: str | None = Field(
        default=None,
        description="Reason shown when the conversation was handed to human support.",
    )
    human_handoff_locked: bool = Field(
        default=False,
        description="Whether the current session can no longer be escalated to a human agent.",
    )
    linked_order_id: UUID | None = Field(
        default=None,
        description="Linked order/shipment for the current support-chat session.",
    )
    linked_order_tracking_code: str | None = Field(
        default=None,
        description="Tracking code for the linked order/shipment.",
    )


class ConversationMessage(BaseModel):
    role: str = Field(description="'user' or 'assistant'")
    message: str
    intent: str | None = None
    sql_generated: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


class ConversationHistory(BaseModel):
    session_id: UUID
    messages: list[ConversationMessage]


class SessionListItem(BaseModel):
    session_id: UUID
    last_message: str
    message_count: int
    created_at: datetime


class SessionListResponse(BaseModel):
    sessions: list[SessionListItem]


class SupportAgentSummary(BaseModel):
    id: UUID
    name: str
    email: str | None = None

    model_config = {"from_attributes": True}


class ContactSubmissionResponse(BaseModel):
    id: UUID
    reference_code: str
    name: str
    email: str
    phone: str | None = None
    subject: str
    category: str
    message: str
    priority: str
    status: str
    notes: str | None = None
    assigned_to_user_id: UUID | None = None
    assigned_agent_name: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ContactSubmissionStats(BaseModel):
    total: int
    new: int
    in_progress: int
    resolved: int
    urgent: int


class ContactSubmissionListResponse(BaseModel):
    submissions: list[ContactSubmissionResponse]
    stats: ContactSubmissionStats
    agents: list[SupportAgentSummary]


class SupportSessionEscalationSummary(BaseModel):
    id: UUID
    status: str
    reason: str
    escalated_at: datetime
    resolved_at: datetime | None = None
    escalated_to_user_id: UUID | None = None
    assigned_agent_name: str | None = None


class SupportSessionListItem(BaseModel):
    session_id: UUID
    user_id: UUID
    user_name: str
    user_email: str | None = None
    user_role: str | None = None
    user_phone: str | None = None
    first_message_at: datetime
    last_message: str
    last_message_role: str
    last_message_at: datetime
    message_count: int
    latest_order_tracking_code: str | None = None
    sentiment: str | None = None
    human_agent_engaged: bool = False
    assigned_agent_name: str | None = None
    needs_human_attention: bool = False
    attention_reason: str | None = None
    escalation: SupportSessionEscalationSummary | None = None


class SupportSessionListResponse(BaseModel):
    sessions: list[SupportSessionListItem]


class SupportConversationMessage(BaseModel):
    id: UUID
    role: str
    message: str
    intent: str | None = None
    created_at: datetime
    author_name: str | None = None
    author_role: str | None = None

    model_config = {"from_attributes": True}


class SupportSessionDetail(BaseModel):
    session: SupportSessionListItem
    messages: list[SupportConversationMessage]


class SupportDashboardStats(BaseModel):
    total_sessions: int
    active_sessions: int
    human_engaged_sessions: int
    sessions_needing_human: int
    open_escalations: int
    open_contact_forms: int
    new_contact_forms: int
    resolved_contact_forms: int
    user_messages_today: int
    assistant_messages_today: int


class SupportDashboardFeedItem(BaseModel):
    id: str
    type: str
    title: str
    description: str
    created_at: datetime


class SupportDashboardResponse(BaseModel):
    stats: SupportDashboardStats
    priority_sessions: list[SupportSessionListItem]
    recent_contact_submissions: list[ContactSubmissionResponse]
    activity_feed: list[SupportDashboardFeedItem]


class SupportAnalyticsMetric(BaseModel):
    id: str
    label: str
    icon: str
    value: float
    formatted_value: str
    trend: str
    trend_direction: str


class SupportAnalyticsResolutionChart(BaseModel):
    labels: list[str]
    ai_resolved: list[int]
    human_escalated: list[int]


class SupportAnalyticsEscalationReason(BaseModel):
    label: str
    count: int
    pct: int


class SupportAnalyticsSentimentChart(BaseModel):
    labels: list[str]
    ai_handled: list[float]
    human_handled: list[float]


class SupportAnalyticsInsight(BaseModel):
    id: str
    icon: str
    title: str
    text: str
    tone: str = Field(description="purple, blue, amber, red, or green")
    action_label: str = "Take Action"
    executed: bool = False


class SupportAnalyticsResponse(BaseModel):
    range: str
    generated_at: datetime
    metrics: list[SupportAnalyticsMetric]
    resolution_chart: SupportAnalyticsResolutionChart
    escalation_reasons: list[SupportAnalyticsEscalationReason]
    sentiment_chart: SupportAnalyticsSentimentChart
    insights: list[SupportAnalyticsInsight]


class SupportAnalyticsInsightExecutionResponse(BaseModel):
    insight_id: str
    ticket_id: UUID
    ticket_reference_code: str
    message: str


class SupportIntegrationStatus(BaseModel):
    provider: str
    label: str
    description: str
    connected: bool
    connection_source: str
    status_note: str
    editable: bool = False


class SupportSettings(BaseModel):
    tone: str = Field(..., min_length=2, max_length=60)
    language_mode: str = Field(..., min_length=2, max_length=60)
    sentiment_threshold: int = Field(..., ge=0, le=100)
    refund_limit_inr: int = Field(..., ge=0, le=500000)
    system_prompt: str = Field(..., min_length=20, max_length=20000)
    autonomous_replies: bool = True
    legal_threat_detection: bool = True
    real_time_sentiment_analysis: bool = True
    proactive_human_handover: bool = False


class SupportSettingsResponse(BaseModel):
    settings: SupportSettings
    integrations: list[SupportIntegrationStatus]
    updated_at: datetime | None = None
    autonomous_reply_guidance: str
    rag_recommended: bool


# ── Escalation Schemas ────────────────────────────────────────────────────────

class EscalateRequest(BaseModel):
    reason: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Why this conversation needs human attention.",
    )


class EscalationResponse(BaseModel):
    id: UUID
    conversation_id: UUID
    reason: str
    escalated_to_user_id: UUID | None = None
    escalated_at: datetime
    resolved_at: datetime | None = None
    status: str

    model_config = {"from_attributes": True}


class EscalationListResponse(BaseModel):
    escalations: list[EscalationResponse]


# ── Enriched Escalation (for Escalation Center UI) ────────────────────────────

class EscalationDetailItem(BaseModel):
    id: UUID
    conversation_id: UUID
    session_id: UUID
    reason: str
    status: str
    escalated_at: datetime
    resolved_at: datetime | None = None
    customer_name: str
    customer_email: str | None = None
    customer_role: str | None = None
    latest_order_tracking_code: str | None = None
    sentiment: str
    assigned_agent_name: str | None = None

    model_config = {"from_attributes": True}


class EscalationDetailListResponse(BaseModel):
    escalations: list[EscalationDetailItem]
    open_count: int
    resolved_count: int


# ── Support Ticket Schemas ─────────────────────────────────────────────────────

class TicketCreate(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    description: str = Field(..., min_length=1)
    priority: str = Field(default="medium")
    category: str = Field(default="general")
    customer_name: str | None = None


class TicketUpdate(BaseModel):
    status: str | None = None
    priority: str | None = None
    category: str | None = None
    notes: str | None = None
    assigned_to_user_id: UUID | None = None
    resolution_action: str | None = None


class TicketReplyItem(BaseModel):
    from_name: str
    message: str
    created_at: datetime


class TicketResponse(BaseModel):
    id: UUID
    reference_code: str
    title: str
    description: str
    priority: str
    status: str
    category: str
    customer_name: str | None = None
    notes: str | None = None
    assigned_to_user_id: UUID | None = None
    assigned_agent_name: str | None = None
    created_at: datetime
    updated_at: datetime
    resolved_at: datetime | None = None
    source: str = "manual"
    source_label: str = "Manual"
    requester_type: str | None = None
    issue_type: str | None = None
    resolution_action: str | None = None
    resolution_label: str | None = None
    linked_vendor_ticket_id: UUID | None = None
    linked_vendor_ticket_code: str | None = None
    linked_damage_report_id: UUID | None = None
    linked_order_id: UUID | None = None
    linked_order_tracking_code: str | None = None
    linked_vendor_replies: list[TicketReplyItem] = []
    can_delete: bool = True
    lm_action_steps: list[str] = []

    model_config = {"from_attributes": True}


class TicketStats(BaseModel):
    total: int
    new: int
    in_progress: int
    resolved: int
    urgent: int


class TicketListResponse(BaseModel):
    tickets: list[TicketResponse]
    stats: TicketStats
    agents: list[SupportAgentSummary]


# ── AI Support — Reverse Logistics (Damage Reports) ───────────────────────────

class SupportMessageItem(BaseModel):
    text: str
    sent_by: str
    sent_at: str


class SupportMessageCreate(BaseModel):
    text: str = Field(..., min_length=1, max_length=2000)
    sent_by: str = Field(default="Support Agent", max_length=100)


class SupportDamageReportItem(BaseModel):
    id: UUID
    reference_code: str
    customer_id: UUID
    customer_name: str
    customer_email: str | None = None
    order_id: UUID | None = None
    order_tracking_code: str | None = None
    description: str
    photos: list[str] = []
    flow_type: str
    status: str
    support_notes: str | None = None
    support_messages: list[SupportMessageItem] = []
    sentiment: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class SupportDamageReportCreate(BaseModel):
    customer_id: UUID
    order_id: UUID | None = None
    description: str = Field(..., min_length=5, max_length=5000)
    flow_type: str = Field(default="photo_review")


class SupportDamageReportNotesUpdate(BaseModel):
    support_notes: str = Field(default="", max_length=5000)


class SupportDamageReportStats(BaseModel):
    total: int
    reported: int
    photo_review: int
    pickup_inspection: int
    under_review: int


class SupportDamageReportListResponse(BaseModel):
    reports: list[SupportDamageReportItem]
    stats: SupportDamageReportStats


# ── AI Support — Refund Center ────────────────────────────────────────────────

class SupportRefundCaseItem(BaseModel):
    id: UUID
    reference_code: str
    customer_name: str
    customer_id: UUID | None = None
    order_id: UUID | None = None
    original_price: float
    refund_amount: float
    status: str
    flow_type: str
    is_urgent: bool = False
    urgent_reason: str | None = None
    support_notes: str | None = None
    sentiment: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class SupportRefundCaseUrgentUpdate(BaseModel):
    is_urgent: bool
    urgent_reason: str | None = Field(default=None, max_length=1000)


class SupportRefundCaseStats(BaseModel):
    total_refunded_value: float
    pending_decision: int
    urgent_count: int


class SupportRefundCaseListResponse(BaseModel):
    cases: list[SupportRefundCaseItem]
    stats: SupportRefundCaseStats


# ── AI Support — Customer History ─────────────────────────────────────────────

class CustomerHistoryResponse(BaseModel):
    total_orders: int
    damage_reports_count: int
    escalations_count: int
    last_sentiment: str | None = None
